### ISSUE TITLE
There is an issue with some ttf font like IranNastaliq

### ISSUE THREAD

**Issue by HamidMp** [omid/Persian-Log2Vis#5]
Hi, I have an issue with some ttf fonts like IranNastaliq, Shekasteh etc
following image is result of:

> این متن کامل است و طولانی
خط دوم

<a href="http://uupload.ir/" target="_blank"><img src="http://uupload.ir/files/a1y5_farsi2.png" border="0" alt="عکس نمونه" /></a>

**Comment by omid** [comment]
Hi,
It's not related to the algorithm, it's related to the fonts that you are using. They are not well designed :-( (Or designed for a specific software or ...)
