### ISSUE TITLE
Doesn't support some Arabic letters 

### ISSUE THREAD

**Issue by zyo00ody** [omid/Persian-Log2Vis#6]
Hi @omid 
Thank you for your great script
It just need a little improvement.

Just try this word    :     ٱللَّهُمَّ

and thank you

**Comment by zyo00ody** [comment]
also it doesn't support this in Arabic :  ،

**Comment by zyo00ody** [comment]
Also it have an issue in this word : شيء 
it prints: شيـء

**Comment by omid** [comment]
Sorry for my late reply.

As you can see, I don't care about this project too much and code base and structure is tooooo old now.

And I used to use my own library to interpret logical to visual strings, but I've found a better library and used that one (which included in TCPDF library @ https://github.com/tecnickcom/tc-lib-pdf )

So, if you can merge the newest version of TCPDF library to this library, I would be happy and thankful to merge your PR (pull request)

**Comment by zyo00ody** [comment]
Thank you very much.
And I'm sorry I'm very beginner in PHP and also github, so I don't know how
to merge these scripts.


Persian-Log2Vis is very very good script , and I think it is best script
for writing Arabic and Persian in php image.

I just need to add : "ء" and "،" to ignore list so it will be not connected
with the letter before it.

see this is the problem:
https://www.yanbuweather.com/moon/moon/example.php

it should be :  شيء

if you can fix it, thank you.



And sorry for my bad English.

2017-09-03 2:23 GMT+03:00 Omid Rad <notifications@github.com>:

**Comment by omid** [comment]
You're welcome. No, your English is fine.

So maybe you can use/test TCPDF library at first and generate a PDF and then convert PDF ti image.

**Comment by zyo00ody** [comment]
Thank you very much. I'll test it,  in sha'a Allah.
Thank you.

بتاريخ ٠٤‏/٠٩‏/٢٠١٧ ٢:٣٦ م، كتب "Omid Rad" <notifications@github.com>:
