### ISSUE TITLE
 #Pashto: Not working with the Pashto language properly.

### ISSUE THREAD

**Issue by rafimuhammadi** [omid/Persian-Log2Vis#9]
Not working with the Pashto language properly.

**Comment by rafimuhammadi** [comment]
![Uploading Screenshot 2024-05-20 111753.png…]()

**Comment by rafimuhammadi** [comment]
![Screenshot 2024-05-20 111753](https://github.com/omid/Persian-Log2Vis/assets/107848881/42b2c790-e355-4d45-99b6-191faa4f9884)

**Comment by omid** [comment]
Unfortunately this project is not active anymore and I don't maintain it anymore.
Anyway. I'm open to any suggestion.

**Comment by rafimuhammadi** [comment]
I have used it in Laravel and I have also added the Pashto font, but it is not working. Please help me to solve it. I will be grateful because it is being implemented in a very important project.

**Comment by omid** [comment]
I don't use PHP anymore. It's very costly for me to switch.
If you can support the cost, we can continue.

**Comment by rafimuhammadi** [comment]
Provide information about its cost and time.

**Comment by omid** [comment]
I couldn't find any email from you.
Please contact me via my email, `omidmr` in the gmail service.

**Comment by rafimuhammadi** [comment]
Please give me your email address or other contact number.

**Comment by omid** [comment]
I mentioned that in my previous message:
> Please contact me via my email, `omidmr` in the gmail service.
